version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - picle_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2504200214052002
      - POSTGRES_DB=newsengine_django
    ports:
    - 5432:5432

  redis:
    image: redis
    ports:
    - 6379:6379

volumes:
  picle_data: