# Generated by Django 3.1.1 on 2020-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, help_text="Головні категорії відображаються на початковій сторінці та є обов'язковими", verbose_name='Чи головна категорія'),
        ),
    ]
