# Generated by Django 3.1.1 on 2020-10-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_category_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час перегляду новини')),
                ('is_checked_on_site', models.BooleanField(default=True, verbose_name='Чи була переглянута на сайті')),
                ('is_checked_on_email', models.BooleanField(default=False, verbose_name='Чи була переглянута на пошті')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія перегляду новин',
                'verbose_name_plural': 'Історії перегляду новин',
            },
        ),
    ]
