# Generated by Django 3.1.1 on 2020-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='is_checked_on_email',
        ),
        migrations.RemoveField(
            model_name='history',
            name='is_checked_on_site',
        ),
        migrations.AddField(
            model_name='history',
            name='checked_on',
            field=models.CharField(choices=[('site', 'На сайті'), ('email', 'На пошті'), ('telegram', 'В телеграмі'), ('app', 'У мобільній програмі')], default='site', help_text='Де користувач переглянув дану новину', max_length=8, verbose_name='Переглянуто на '),
        ),
    ]
