# Generated by Django 3.1.1 on 2020-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(help_text='Категорії, які користувач відслідковує', related_name='users', to='news.Category'),
        ),
    ]
