# Generated by Django 3.1.1 on 2020-11-04 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_user_checked_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countdown_to_email',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Найменший період між відправленнями новин на пошту', verbose_name='Відрізок часу між відправкою новин на пошту'),
        ),
    ]
