# Generated by Django 3.1.1 on 2020-11-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('news', '0006_history'),
        ('auth_system', '0006_user_countdown_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='countdown_to_email',
            new_name='_countdown_to_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='send_news_to_email',
            new_name='_send_news_to_email',
        ),
        migrations.AddField(
            model_name='user',
            name='email_periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name="Зв'язана задача по відправці новин на пошту"),
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Категорії, які користувач відслідковує', related_name='users', to='news.Category'),
        ),
    ]
