# Generated by Django 3.1.1 on 2020-11-20 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201118_1103'),
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('auth_system', '0007_auto_20201109_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.AddField(
            model_name='user',
            name='_countdown_to_telegram',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Найменший період між відправленнями новин в телеграм', verbose_name='Відрізок часу між відправкою новин в в телеграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='_send_news_to_telegram',
            field=models.BooleanField(default=False, help_text='Активуйте, якщо хочете отримувати новини в телеграмі', verbose_name='Надсилати новини на в телеграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories_email',
            field=models.ManyToManyField(blank=True, help_text='Категорії, новини з яких користувач хоче бачити на пошті', related_name='users_email', to='news.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories_telegram',
            field=models.ManyToManyField(blank=True, help_text='Категорії, новини з яких користувач хоче бачити на в телеграмі', related_query_name='users_telegram', to='news.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_telegram', to='django_celery_beat.periodictask', verbose_name="Зв'язана задача по відправці новин в телеграм"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_email', to='django_celery_beat.periodictask', verbose_name="Зв'язана задача по відправці новин на пошту"),
        ),
    ]
